// header/src/shared/components/Counter/index.tsx
import React from 'react';
import { Button, Typography, Card } from '@mui/material';
import { observer } from 'mobx-react-lite';

import { useStore } from 'host/Store';

type CounterProps = {
  children?: React.ReactNode;
};

export const Counter = observer(({}: CounterProps) => {
  const { counter } = useStore();

  return (
    <Card sx={{ marginTop: 3, padding: 3 }}>
      <Typography variant="h4">ReactJs Counter</Typography>
      <Typography variant="h6" sx={{ marginTop: 1 }}>
        {counter.count}
      </Typography>
      <Button variant="contained" color="error" size="medium" onClick={() => counter.decrement()} sx={{ marginTop: 2 }}>
        Decrement
      </Button>
      <Button
        variant="contained"
        color="success"
        size="medium"
        onClick={() => counter.increment()}
        sx={{ marginTop: 2, marginLeft: 2 }}
      >
        Increment
      </Button>
    </Card>
  );
});

// svelte-counter/src/components/Counter.svelte
<script context="module">
  import { connect } from 'svelte-mobx';
</script>

<script lang="ts">
  import Button, { Label } from '@smui/button';
  import Card, { Content } from '@smui/card';

  import { useStore } from 'host/Store';

  const { autorun } = connect();
  let { counter } = useStore();

  let count: number;
  function increment() { counter.increment() };
  function decrement() { counter.decrement() };

  autorun(() => {
    count = counter.count;
  });
</script>

<Card marginheight={20}>
  <Content>
    <h1 class="mdc-typography--headline4">Svelte Counter</h1>
    <h2 class="mdc-typography--headline5">{count}</h2>
    <Button color="secondary" variant="raised" on:click={decrement}><Label>Decrement</Label></Button>
    <Button color="primary" variant="raised" on:click={increment}><Label>Increment</Label></Button>
  </Content>
</Card>

<style>
  h1 {
    margin-top: 0px;
    margin-bottom: 0px;
    font-weight: 400;
  }
  h2 {
    margin-top: 8px;
    margin-bottom: 8px;
  }
</style>
